site_name: Effective Dreamweave Lua
repo_url: https://github.com/DreamWeave-MP/effective-dreamweave-lua
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.expand
        - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
    - 'index.md'
    - 'structure.md'
    - 'functions.md'
    - 'events.md'
    - 'tables.md'
    - 'variables.md'
    - 'conditionals.md'
